// Each level teaches a structural engineering concept
// hDiff: positive = right anchor is LOWER than left
//
// ALL gaps, hDiffs, and anchor offsets are multiples of GRID (36px)
//
// PROGRESSION:
//   Ch 1 (L1-4):  wood_road + wood_beam — bicycle, car
//   Ch 2 (L5-6):  + steel — sports_car, jeep
//   Ch 3 (L7-8):  + cable + rope — corolla, datsun
//   Ch 4 (L9-10): + reinforced_road — truck, camper
//   Ch 5 (L11-12): + stone_road — bus
//   Ch 6 (L13-15): all materials — flatbed, boat_trailer, multi-vehicle

export const LEVELS = [
    // ═══ CHAPTER 1: WOOD & BASICS ═══════════════════
    {
        id:       "first",
        name:     "CASUAL CROSS",
        concept:  "BASICS",
        gimmick:  "road",
        difficulty: 1,
        vType:    "car",
        gap:      360,
        hDiff:    0,
        budget:   7000,
        terrain:  "canyon",
        extraAnchors: [],
        multiVehicle: null,
        materials: ["wood_road", "wood_beam"],
        hint:     "Lay wood planks anchor-to-anchor for the road, then add beams underneath so the car doesn't snap them. Two anchors, flat ground — easy crossing.",
        lesson:   "Every bridge needs a ROAD surface for vehicles and BEAMS for support. Wood planks are your road — beams hold them up so they don't sag and break under a car's weight.",
    },
    {
        id:       "triangle",
        name:     "TRIANGLE POWER",
        concept:  "TRIANGLES",
        gimmick:  "triangle",
        difficulty: 1,
        vType:    "car",
        gap:      288,
        hDiff:    0,
        budget:   5500,
        terrain:  "canyon",
        extraAnchors: [],
        multiVehicle: null,
        materials: ["wood_road", "wood_beam"],
        hint:     "Build triangles underneath the road. Triangles are rigid — they can't collapse like rectangles.",
        lesson:   "A triangle is the strongest shape in engineering. Unlike rectangles, a triangle can't change its angles without breaking a side. This is TRIANGULATION.",
    },
    {
        id:       "stretch",
        name:     "LONG STRETCH",
        concept:  "SPAN",
        gimmick:  "wide",
        difficulty: 2,
        vType:    "car",
        gap:      432,
        hDiff:    0,
        budget:   10000,
        terrain:  "canyon",
        extraAnchors: [],
        multiVehicle: null,
        materials: ["wood_road", "wood_beam"],
        hint:     "A longer span sags more. Use repeated triangles (a TRUSS) to spread the load evenly across the whole bridge.",
        lesson:   "A TRUSS is a framework of triangles. As spans get longer, single triangles aren't enough — you need a repeating pattern that distributes force along the entire length.",
    },
    {
        id:       "ramp",
        name:     "THE RAMP",
        concept:  "SLOPES",
        gimmick:  "slope",
        difficulty: 2,
        vType:    "datsun",
        gap:      396,
        hDiff:    108,
        budget:   9000,
        terrain:  "cliff",
        extraAnchors: [],
        multiVehicle: null,
        materials: ["wood_road", "wood_beam"],
        hint:     "Sloped bridges feel a sideways push. Brace diagonally to resist this THRUST — don't just build straight down.",
        lesson:   "Sloped bridges experience THRUST — gravity pulls down, but the slope redirects force sideways. Diagonal bracing transfers thrust safely into the anchors.",
    },

    // ═══ CHAPTER 2: INTRODUCING STEEL ═══════════════
    {
        id:       "steelintro",
        name:     "IRON WILL",
        concept:  "STEEL",
        gimmick:  "steel",
        difficulty: 2,
        vType:    "sports_car",
        gap:      360,
        hDiff:    0,
        budget:   12000,
        terrain:  "canyon",
        extraAnchors: [],
        multiVehicle: null,
        materials: ["wood_road", "wood_beam", "steel"],
        hint:     "You now have STEEL beams. They're expensive but far stronger. Try using steel only where stress is highest — the center and bottom of your truss.",
        lesson:   "Steel is 4× stronger than wood but costs more. Smart engineers use the strongest material only where STRESS peaks, not everywhere. This is called MATERIAL OPTIMIZATION.",
    },
    {
        id:       "steepfall",
        name:     "STEEP FALL",
        concept:  "THRUST + STEEL",
        gimmick:  "slope",
        difficulty: 3,
        vType:    "jeep",
        gap:      432,
        hDiff:    180,
        budget:   15000,
        terrain:  "cliff",
        extraAnchors: [],
        multiVehicle: null,
        materials: ["wood_road", "wood_beam", "steel"],
        hint:     "This steep slope creates massive thrust. Steel at the key stress points will prevent buckling where wood would snap.",
        lesson:   "Steep slopes multiply THRUST forces. When wood isn't strong enough, steel reinforcement at critical joints prevents BUCKLING — when a beam crumples under compression.",
    },

    // ═══ CHAPTER 3: CABLES & ROPE ═══════════════════
    {
        id:       "string",
        name:     "STRING THEORY",
        concept:  "TENSION",
        gimmick:  "cable",
        difficulty: 2,
        vType:    "corolla",
        gap:      396,
        hDiff:    0,
        budget:   11000,
        terrain:  "canyon",
        extraAnchors: [
            { side: "L", dx: 0, dy: -108 },
            { side: "R", dx: 0, dy: -108 },
        ],
        multiVehicle: null,
        materials: ["wood_road", "wood_beam", "rope"],
        hint:     "Use the HIGH anchor points and rope to pull the road UP from above. Rope only works when stretched — it goes slack if compressed.",
        lesson:   "Rope and cables work only in TENSION (pulling). They're light and strong but can't push. A suspension bridge hangs the road from cables attached above!",
    },
    {
        id:       "suspend",
        name:     "HANG IN THERE",
        concept:  "SUSPENSION",
        gimmick:  "cable",
        difficulty: 3,
        vType:    "datsun",
        gap:      468,
        hDiff:    0,
        budget:   16000,
        terrain:  "canyon",
        extraAnchors: [
            { side: "L", dx: 0, dy: -108 },
            { side: "R", dx: 0, dy: -108 },
        ],
        multiVehicle: null,
        materials: ["wood_road", "wood_beam", "steel", "rope", "cable"],
        hint:     "Combine steel cables from above with a stiff truss deck below. Cables take tension, the truss resists bending — together they span farther.",
        lesson:   "A true SUSPENSION bridge combines cables (tension), a stiff deck (bending resistance), and anchorages. This system lets bridges span enormous distances!",
    },

    // ═══ CHAPTER 4: REINFORCED ROADS & HEAVY LOADS ══
    {
        id:       "gorge",
        name:     "DEEP VALLEY",
        concept:  "PIERS",
        gimmick:  "pier",
        difficulty: 3,
        vType:    "truck",
        gap:      504,
        hDiff:    0,
        budget:   20000,
        terrain:  "gorge",
        extraAnchors: [
            { side: "L", dx: 0, dy: 108 },
            { side: "L", dx: 0, dy: 216 },
            { side: "R", dx: 0, dy: 108 },
            { side: "R", dx: 0, dy: 216 },
        ],
        multiVehicle: null,
        materials: ["wood_road", "reinforced_road", "wood_beam", "steel"],
        hint:     "Use the wall anchors BELOW to build vertical piers up to road level. A delivery van is crossing — use reinforced road for the heaviest spans!",
        lesson:   "PIERS are vertical supports built from below. They break a long span into shorter sections, each easier to bridge. This is how most real highway bridges work!",
    },
    {
        id:       "heavy",
        name:     "HEAVY LOAD",
        concept:  "REINFORCEMENT",
        gimmick:  "heavy",
        difficulty: 3,
        vType:    "camper",
        gap:      396,
        hDiff:    0,
        budget:   18000,
        terrain:  "canyon",
        extraAnchors: [],
        multiVehicle: null,
        materials: ["wood_road", "reinforced_road", "wood_beam", "steel", "cable"],
        hint:     "No piers this time — span the full gap for a heavy camper van. Reinforced road + steel beams at critical spots.",
        lesson:   "When you can't build piers, the structure itself must be stronger. REINFORCEMENT means adding material where forces concentrate — usually at the center and supports.",
    },

    // ═══ CHAPTER 5: STONE ROADS & ADVANCED ══════════
    {
        id:       "budget",
        name:     "PENNY PINCH",
        concept:  "EFFICIENCY",
        gimmick:  "budget",
        difficulty: 3,
        vType:    "car",
        gap:      396,
        hDiff:    0,
        budget:   4500,
        terrain:  "canyon",
        extraAnchors: [],
        multiVehicle: null,
        materials: ["wood_road", "wood_beam"],
        hint:     "Tiny budget, wood only. Every beam costs money. Find the absolute minimum structure that still holds a car.",
        lesson:   "The best engineering isn't the strongest bridge — it's the one that's JUST strong enough. Efficiency means using the minimum material for the required load.",
    },
    {
        id:       "zigzag",
        name:     "SWITCHBACK",
        concept:  "STEEP + PIERS",
        gimmick:  "slope",
        difficulty: 4,
        vType:    "bus",
        gap:      468,
        hDiff:    180,
        budget:   28000,
        terrain:  "gorge",
        extraAnchors: [
            { side: "L", dx: 0, dy: 144 },
            { side: "R", dx: 0, dy: 144 },
        ],
        multiVehicle: null,
        materials: ["wood_road", "reinforced_road", "stone_road", "wood_beam", "steel", "rope", "cable"],
        hint:     "Steep slope + deep gorge + heavy bus. Use stone road for the bus, wall anchors for piers, and steel where stress is worst.",
        lesson:   "Real bridges often face MULTIPLE challenges at once: slopes, heavy loads, deep valleys. The best engineers combine piers, trusses, cables, and material choices.",
    },

    // ═══ CHAPTER 6: BOSS LEVELS ═════════════════════
    {
        id:       "highway",
        name:     "RUSH HOUR",
        concept:  "MULTI-LOAD",
        gimmick:  "multi",
        difficulty: 4,
        vType:    "car",
        gap:      468,
        hDiff:    0,
        budget:   22000,
        terrain:  "canyon",
        extraAnchors: [],
        multiVehicle: [
            { vType: "jeep",       startXOffset: -72,  label: "A", color: "#e890a0" },
            { vType: "sports_car", startXOffset: -144, label: "B", color: "#d4b020" },
        ],
        materials: ["wood_road", "reinforced_road", "wood_beam", "steel", "cable"],
        hint:     "Two vehicles cross at the same time! Your bridge must hold both simultaneously.",
        lesson:   "Real bridges carry MANY vehicles at once. When multiple loads are present, forces ADD UP. Your structure needs enough redundancy that no single member is a weak link.",
    },
    {
        id:       "express",
        name:     "THE EXPRESS",
        concept:  "MASTERY",
        gimmick:  "heavy",
        difficulty: 5,
        vType:    "flatbed",
        gap:      540,
        hDiff:    0,
        budget:   38000,
        terrain:  "gorge",
        extraAnchors: [
            { side: "MID", dx: -108, dy: 216 },
            { side: "MID", dx:    0, dy: 216 },
            { side: "MID", dx:  108, dy: 216 },
        ],
        multiVehicle: null,
        materials: ["wood_road", "reinforced_road", "stone_road", "wood_beam", "steel", "rope", "cable"],
        hint:     "A flatbed truck — the heaviest vehicle. Build piers from the valley floor and use stone road with a full steel truss.",
        lesson:   "Heavy transport bridges are over-engineered on purpose — trucks are heavy and can't steer around problems. REDUNDANCY (extra strength beyond the minimum) saves lives.",
    },
    {
        id:       "finale",
        name:     "GRAND FINALE",
        concept:  "EVERYTHING",
        gimmick:  "multi",
        difficulty: 5,
        vType:    "truck",
        gap:      612,
        hDiff:    108,
        budget:   45000,
        terrain:  "gorge",
        extraAnchors: [
            { side: "L", dx: 0, dy: -108 },
            { side: "R", dx: 0, dy: -108 },
            { side: "L", dx: 0, dy: 144 },
            { side: "R", dx: 0, dy: 144 },
        ],
        multiVehicle: [
            { vType: "bus",       startXOffset: -72,  label: "A", color: "#d4a020" },
            { vType: "camper",    startXOffset: -180, label: "B", color: "#5a9a5a" },
            { vType: "sports_car", startXOffset: -288, label: "C", color: "#d4b020" },
        ],
        materials: ["wood_road", "reinforced_road", "stone_road", "wood_beam", "steel", "rope", "cable"],
        hint:     "Sloped gorge, three vehicles, anchors above and below. Combine piers, suspension cables, steel reinforcement, and the right road type for each section.",
        lesson:   "You've mastered bridge engineering! Every real bridge is a puzzle: terrain, loads, materials, and budget. The best engineers find elegant solutions that balance ALL constraints.",
    },
];
